services:
  - type: web
    name: host-backend
    env: python
    region: Oregon (US West)
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn host_backend.wsgi:application

    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "tripnest-backend.onrender.com"
